### ISSUE TITLE
KeyError: 'video_video_reward'

### ISSUE THREAD

**Issue by yansuoyuli** [mazpie/genrl#4]
Hello! When I run the command: python3 train.py task=stickman_walk snapshot_load_dir=models/genrl_stickman_500k_2.pt num_train_frames=50_010 batch_size=32 batch_length=32 agent.imag_reward_fn=video_video_reward eval_modality=task_imag 

It occurs:
File "genrl/agent/genrl.py", line 122, in <lambda>
    imag_reward_fn = lambda seq: globals()[self.cfg.imag_reward_fn](self, seq, **self.cfg.imag_reward_args)
KeyError: 'video_video_reward'

**Comment by yansuoyuli** [comment]
Traceback (most recent call last):
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "genrl/train.py", line 468, in main
    start_training(cfg, None, None)
  File "genrl/train.py", line 464, in start_training
    workspace.train()
  File "genrl/train.py", line 357, in train
    metrics.update(self.agent.update_imag_behavior(state=None, outputs=outputs, metrics=metrics, seq_data=batch_data,)[1])
  File "genrl/agent/genrl.py", line 123, in update_imag_behavior
    metrics.update(self._imag_behavior.update(self.wm, start, is_terminal, imag_reward_fn,))
  File "genrl/agent/dreamer.py", line 377, in update
    reward = reward_fn(seq)
  File "genrl/agent/genrl.py", line 122, in <lambda>
    imag_reward_fn = lambda seq: globals()[self.cfg.imag_reward_fn](self, seq, **self.cfg.imag_reward_args)
KeyError: 'video_video_reward'

**Comment by yansuoyuli** [comment]
And when I run python3 train.py task=stickman_walk snapshot_load_dir=models/genrl_stickman_500k_2.pt num_train_frames=50_010 batch_size=32 batch_length=32 agent.imag_reward_fn=video_text_reward eval_modality=task_imag ;
Code cannot find replay_load_dir:
File "/mnt/disk_1/songli/genrl/train.py", line 468, in main
    start_training(cfg, None, None)
  File "genrl/train.py", line 455, in start_training
    workspace = W(cfg, savedir, workdir)
  File "genrl/train.py", line 108, in __init__
    replay_dir = Path(cfg.replay_load_dir)
  File "genrl/lib/python3.10/pathlib.py", line 958, in __new__
    self = cls._from_parts(args)
  File "genrl/lib/python3.10/pathlib.py", line 592, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "genrl/lib/python3.10/pathlib.py", line 576, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by yansuoyuli** [comment]
Thank you for the reminder. However, it seems that several keys are missing:

- `multistep = kwargs['multistep']`
- `align_initial = kwargs['align_initial']`
- `conditional_coeff = kwargs['conditional_coeff']`
- `sample_for_target = kwargs['sample_for_target']`
- `skip_first_target = kwargs['skip_first_target']`

The error occurs in the file `genrl/tools/genrl_utils.py`, line 380, as indicated by the traceback:

File "genrl/tools/genrl_utils.py", line 380, in video_video_reward
    multistep = kwargs['multistep']
KeyError: 'multistep'

File "genrl/tools/genrl_utils.py", line 380, in video_video_reward
    conditional_coeff = kwargs['conditional_coeff']
KeyError: 'conditional_coeff'

**Comment by mazpie** [comment]
Some args were probably removed/renamed between development and the public code. I will look into this soon! 

Sorry, it may take a while

**Comment by yansuoyuli** [comment]
Hello! I hope you're doing well. I wanted to check if there have been any updates. Thank you!

**Comment by mazpie** [comment]
Hi @yansuoyuli ,

Sorry for the delay. I have just fixed the issue in the last commit
