### ISSUE TITLE
Problems when change the task

### ISSUE THREAD

**Issue by yansuoyuli** [mazpie/genrl#7]
When I run the following code, it goes wrong:
python3 train.py task=kitchen_microwave replay_load_dir=data/stickman_example num_train_frames=500_010 visual_every_frames=25_000 train_world_model=True train_connector=True reset_world_model=True reset_connector=True

python3 train.py task=kitchen_light replay_load_dir=data/stickman_example num_train_frames=500_010 visual_every_frames=25_000 train_world_model=True train_connector=True reset_world_model=True reset_connector=True

Traceback (most recent call last):
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "genrl-main/train.py", line 451, in main
    start_training(cfg, None, None)
  File "genrl-main/train.py", line 438, in start_training
    workspace = W(cfg, savedir, workdir)
  File "genrl-main/train.py", line 60, in __init__
    self.train_env = envs.make(task, cfg.obs_type, cfg.action_repeat, cfg.seed, img_size=img_size,  viclip_encode=cfg.viclip_encode, clip_hd_rendering=cfg.clip_hd_rendering)
  File "genrl-main/envs/main.py", line 716, in make
    env = TimeLimit(KitchenWrapper(task, seed=seed, action_repeat=action_repeat, size=(img_size,img_size)), 280 // action_repeat)
  File "genrl-main/envs/main.py", line 378, in __init__
    self._env  = {
  File "genrl-main/envs/kitchen_extra.py", line 84, in __init__
    super(KitchenBase, self).__init__(**kwargs)
  File "genrl-main/third_party/relay-policy-learning/adept_envs/adept_envs/franka/kitchen_multitask_v0.py", line 181, in __init__
    super(KitchenTaskRelaxV1, self).__init__()
  File "genrl-main/third_party/relay-policy-learning/adept_envs/adept_envs/utils/configurable.py", line 132, in __init__
    base_init(self, *args, **kwargs)
  File "genrl-main/third_party/relay-policy-learning/adept_envs/adept_envs/franka/kitchen_multitask_v0.py", line 46, in __init__
    super().__init__(
  File "genrl-main/third_party/relay-policy-learning/adept_envs/adept_envs/robot_env.py", line 80, in __init__
    super(RobotEnv, self).__init__(
  File "genrl-main/third_party/relay-policy-learning/adept_envs/adept_envs/mujoco_env.py", line 62, in __init__
    self.sim_robot = MujocoSimRobot(
  File "genrl-main/third_party/relay-policy-learning/adept_envs/adept_envs/simulation/sim_robot.py", line 61, in __init__
    self.sim = dm_mujoco.Physics.from_xml_path(model_file)
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/dm_control/mujoco/engine.py", line 461, in from_xml_path
    model = wrapper.MjModel.from_xml_path(file_path)
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/dm_control/mujoco/wrapper/core.py", line 306, in from_xml_path
    model_ptr = _get_model_ptr_from_xml(xml_path=xml_path)
  File "anaconda3/envs/genrl/lib/python3.10/site-packages/dm_control/mujoco/wrapper/core.py", line 181, in _get_model_ptr_from_xml
    ptr = mujoco.MjModel.from_xml_path(xml_path, assets or {})
ValueError: XML Error: top-level default class 'main' cannot be renamed
Element 'default', line 0

    ptr = mujoco.MjModel.from_xml_path(xml_path, assets or {})
ValueError: XML Error: top-level default class 'main' cannot be renamed
Element 'default', line 0

**Comment by mazpie** [comment]
Hi @yansuoyuli,

I think this issue may be due to some problems during the installation process e.g. having a wrong version of Mujoco.

You can try with the following versions:
```
mujoco==3.1.4
mujoco-py==2.1.2.14
```
 
Please, make sure the FrankaKitchen environment is working correctly before launching the experiment. 
The other environments are likely working fine.
